-- APEX Database Schema
-- TimescaleDB hypertables for time-series data

-- Enable TimescaleDB
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ============================================================
-- Core Trading Tables
-- ============================================================

-- Markets tracked across all venues
CREATE TABLE markets (
    id              TEXT PRIMARY KEY,
    venue           TEXT NOT NULL,           -- polymarket, kalshi, tastytrade
    symbol          TEXT NOT NULL,
    title           TEXT,
    category        TEXT,
    resolution_date TIMESTAMPTZ,
    status          TEXT DEFAULT 'active',   -- active, resolved, closed
    outcome         SMALLINT,               -- NULL=unresolved, 1=YES, 0=NO
    metadata        JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_markets_venue_status ON markets (venue, status);
CREATE INDEX idx_markets_category ON markets (category);

-- Signals generated by the ensemble pipeline
CREATE TABLE signals (
    id              BIGSERIAL,
    time            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    market_id       TEXT NOT NULL,
    venue           TEXT NOT NULL,
    strategy        TEXT NOT NULL,
    direction       TEXT NOT NULL,           -- BUY, SELL
    edge            DOUBLE PRECISION NOT NULL,
    edge_ci_lower   DOUBLE PRECISION,
    edge_ci_upper   DOUBLE PRECISION,
    ensemble_score  DOUBLE PRECISION,
    regime          TEXT,
    model_outputs   JSONB DEFAULT '{}',      -- raw model outputs
    accepted        BOOLEAN DEFAULT FALSE,
    reject_reason   TEXT,
    PRIMARY KEY (time, id)
);
SELECT create_hypertable('signals', 'time', chunk_time_interval => INTERVAL '1 day');

-- Trades executed across all venues
CREATE TABLE trades (
    id              TEXT PRIMARY KEY,
    time            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    market_id       TEXT NOT NULL,
    venue           TEXT NOT NULL,
    strategy        TEXT NOT NULL,
    direction       TEXT NOT NULL,
    side            TEXT NOT NULL,            -- ENTRY, EXIT
    price           DOUBLE PRECISION NOT NULL,
    quantity        DOUBLE PRECISION NOT NULL,
    cost            DOUBLE PRECISION NOT NULL,
    fee             DOUBLE PRECISION DEFAULT 0,
    external_id     TEXT,
    signal_id       BIGINT,
    metadata        JSONB DEFAULT '{}'
);
CREATE INDEX idx_trades_time ON trades (time DESC);
CREATE INDEX idx_trades_venue ON trades (venue, time DESC);
CREATE INDEX idx_trades_strategy ON trades (strategy, time DESC);

-- Open positions
CREATE TABLE positions (
    id              TEXT PRIMARY KEY,
    market_id       TEXT NOT NULL,
    venue           TEXT NOT NULL,
    strategy        TEXT NOT NULL,
    direction       TEXT NOT NULL,
    entry_price     DOUBLE PRECISION NOT NULL,
    current_price   DOUBLE PRECISION,
    quantity        DOUBLE PRECISION NOT NULL,
    cost_basis      DOUBLE PRECISION NOT NULL,
    unrealized_pnl  DOUBLE PRECISION DEFAULT 0,
    realized_pnl    DOUBLE PRECISION DEFAULT 0,
    status          TEXT DEFAULT 'open',     -- open, closed
    opened_at       TIMESTAMPTZ DEFAULT NOW(),
    closed_at       TIMESTAMPTZ,
    exit_price      DOUBLE PRECISION,
    metadata        JSONB DEFAULT '{}'
);
CREATE INDEX idx_positions_status ON positions (status, venue);

-- ============================================================
-- Time-Series Hypertables
-- ============================================================

-- Price ticks from all venues
CREATE TABLE price_ticks (
    time            TIMESTAMPTZ NOT NULL,
    venue           TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    bid             DOUBLE PRECISION,
    ask             DOUBLE PRECISION,
    mid             DOUBLE PRECISION NOT NULL,
    volume          DOUBLE PRECISION DEFAULT 0,
    metadata        JSONB
);
SELECT create_hypertable('price_ticks', 'time', chunk_time_interval => INTERVAL '1 hour');
CREATE INDEX idx_price_ticks_lookup ON price_ticks (venue, symbol, time DESC);

-- Orderbook snapshots (L2, top 5 levels)
CREATE TABLE orderbook_snapshots (
    time            TIMESTAMPTZ NOT NULL,
    venue           TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    bids            JSONB NOT NULL,
    asks            JSONB NOT NULL,
    spread          DOUBLE PRECISION,
    imbalance       DOUBLE PRECISION
);
SELECT create_hypertable('orderbook_snapshots', 'time', chunk_time_interval => INTERVAL '1 hour');

-- Feature store: materialized features for offline training
CREATE TABLE feature_store (
    time            TIMESTAMPTZ NOT NULL,
    entity_id       TEXT NOT NULL,
    feature_set     TEXT NOT NULL,
    features        JSONB NOT NULL
);
SELECT create_hypertable('feature_store', 'time', chunk_time_interval => INTERVAL '1 day');
CREATE INDEX idx_feature_store_entity ON feature_store (entity_id, feature_set, time DESC);

-- Portfolio snapshots for risk monitoring
CREATE TABLE portfolio_snapshots (
    time            TIMESTAMPTZ NOT NULL,
    total_equity    DOUBLE PRECISION NOT NULL,
    poly_equity     DOUBLE PRECISION DEFAULT 0,
    kalshi_equity   DOUBLE PRECISION DEFAULT 0,
    tt_equity       DOUBLE PRECISION DEFAULT 0,
    open_positions  INT DEFAULT 0,
    deployed_pct    DOUBLE PRECISION DEFAULT 0,
    drawdown_pct    DOUBLE PRECISION DEFAULT 0,
    cvar_95         DOUBLE PRECISION,
    regime          TEXT,
    breaker_level   TEXT DEFAULT 'GREEN'
);
SELECT create_hypertable('portfolio_snapshots', 'time', chunk_time_interval => INTERVAL '1 day');

-- Weather observations (ground truth for calibration)
CREATE TABLE weather_observations (
    time            TIMESTAMPTZ NOT NULL,
    city            TEXT NOT NULL,
    station         TEXT,
    temp_f          DOUBLE PRECISION NOT NULL,
    humidity        DOUBLE PRECISION,
    wind_mph        DOUBLE PRECISION,
    source          TEXT NOT NULL
);
SELECT create_hypertable('weather_observations', 'time', chunk_time_interval => INTERVAL '1 day');

-- Model performance tracking
CREATE TABLE model_performance (
    time            TIMESTAMPTZ NOT NULL,
    model_name      TEXT NOT NULL,
    model_version   TEXT NOT NULL,
    metric_name     TEXT NOT NULL,
    metric_value    DOUBLE PRECISION NOT NULL,
    metadata        JSONB DEFAULT '{}'
);
SELECT create_hypertable('model_performance', 'time', chunk_time_interval => INTERVAL '1 day');
CREATE INDEX idx_model_perf_lookup ON model_performance (model_name, metric_name, time DESC);

-- Strategy performance daily
CREATE TABLE strategy_performance (
    time            TIMESTAMPTZ NOT NULL,
    strategy        TEXT NOT NULL,
    venue           TEXT NOT NULL,
    trades_count    INT DEFAULT 0,
    wins            INT DEFAULT 0,
    losses          INT DEFAULT 0,
    gross_pnl       DOUBLE PRECISION DEFAULT 0,
    fees            DOUBLE PRECISION DEFAULT 0,
    net_pnl         DOUBLE PRECISION DEFAULT 0,
    sharpe          DOUBLE PRECISION,
    max_drawdown    DOUBLE PRECISION DEFAULT 0,
    avg_edge        DOUBLE PRECISION,
    brier_score     DOUBLE PRECISION
);
SELECT create_hypertable('strategy_performance', 'time', chunk_time_interval => INTERVAL '1 day');

-- ============================================================
-- Data Retention Policies
-- ============================================================

-- Keep price ticks for 90 days
SELECT add_retention_policy('price_ticks', INTERVAL '90 days');

-- Keep orderbook snapshots for 30 days
SELECT add_retention_policy('orderbook_snapshots', INTERVAL '30 days');

-- Keep features for 1 year
SELECT add_retention_policy('feature_store', INTERVAL '365 days');

-- Keep portfolio snapshots forever (small data)
-- Keep weather observations for 2 years
SELECT add_retention_policy('weather_observations', INTERVAL '730 days');

-- ============================================================
-- Continuous Aggregates for performance dashboards
-- ============================================================

CREATE MATERIALIZED VIEW hourly_prices
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', time) AS bucket,
    venue,
    symbol,
    first(mid, time) AS open,
    max(mid) AS high,
    min(mid) AS low,
    last(mid, time) AS close,
    sum(volume) AS volume,
    count(*) AS tick_count
FROM price_ticks
GROUP BY bucket, venue, symbol;

SELECT add_continuous_aggregate_policy('hourly_prices',
    start_offset => INTERVAL '3 hours',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '1 hour');
